### ISSUE TITLE
Plugin can't work technically in any scenario

### ISSUE THREAD

**Issue by Igorrreha** [AppLovin/AppLovin-MAX-Godot#33]
### MAX Plugin Version

1.0.3

### Godot Version

4.x

### Device/Platform Info

Any Android or iOS device

### Current Behavior

Most important file — the plugin singleton is missing in repo, so AppLovinMAX.gd _get_plugin() function allways returns null

`
![image](https://github.com/AppLovin/AppLovin-MAX-Godot/assets/23380802/62f7907a-ed3b-426f-a3c9-8af760944b52)
`

### Expected Behavior

The repo contains plugin singleton code file

### How to Reproduce

1. Download plugin from any source
2. Try to initialize AppLovinMAX

**Comment by Igorrreha** [comment]
Maybe my assumption is false and I can't find the content of the singleton just because its content is in the .aar file

**Comment by Igorrreha** [comment]
Now I found AppLovinMAXGodotPlugin.class file in the android plugin .aar file. Maybe I just make something wrong in attempt to use it in my project

**Comment by Igorrreha** [comment]
Okay, now I see that you are used gd native to create plugin singleton on application start. I still have an issue, but this issue is not valid, so I close it.

```
FATAL EXCEPTION: VkThread
Process: com.godot.game, PID: 28067
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/applovin/sdk/AppLovinAdContentRating;
at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
at java.lang.reflect.Method.getReturnType(Method.java:148)
at java.lang.Class.getDeclaredMethods(Class.java:2728)
at org.godotengine.godot.plugin.GodotPlugin.registerPluginWithGodotNative(GodotPlugin.java:129)
at org.godotengine.godot.plugin.GodotPlugin.onRegisterPluginWithGodotNative(GodotPlugin.java:119)
at org.godotengine.godot.Godot.onInitRenderView$lambda-1(Godot.kt:460)
at org.godotengine.godot.Godot.$r8$lambda$d6wk4TQp77dPW9MpssulyREpzr8(Unknown Source:0)
at org.godotengine.godot.Godot$$ExternalSyntheticLambda8.run(Unknown Source:2)
at org.godotengine.godot.vulkan.VkThread.run(VkThread.kt:219)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.applovin.sdk.AppLovinAdContentRating" on path: DexPathList[[zip file "/data/app/~~yaENJH162GlB9lkptl0snw==/com.godot.game-YIgMbc1gqrw0TW9K7gPBoA==/base.apk"],nativeLibraryDirectories=[/data/app/~~yaENJH162GlB9lkptl0snw==/com.godot.game-YIgMbc1gqrw0TW9K7gPBoA==/lib/arm64, /data/app/~~yaENJH162GlB9lkptl0snw==/com.godot.game-YIgMbc1gqrw0TW9K7gPBoA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method) 
at java.lang.reflect.Method.getReturnType(Method.java:148) 
at java.lang.Class.getDeclaredMethods(Class.java:2728) 
at org.godotengine.godot.plugin.GodotPlugin.registerPluginWithGodotNative(GodotPlugin.java:129) 
at org.godotengine.godot.plugin.GodotPlugin.onRegisterPluginWithGodotNative(GodotPlugin.java:119) 
at org.godotengine.godot.Godot.onInitRenderView$lambda-1(Godot.kt:460) 
at org.godotengine.godot.Godot.$r8$lambda$d6wk4TQp77dPW9MpssulyREpzr8(Unknown Source:0) 
at org.godotengine.godot.Godot$$ExternalSyntheticLambda8.run(Unknown Source:2) 
at org.godotengine.godot.vulkan.VkThread.run(VkThread.kt:219) 
```

**Comment by Igorrreha** [comment]
-
